#version: '2'
#services:
#    dockerapp:
#        restart: always
#        build: .
#        ports:
#            - "5000:5000"
#        volumes:
#            - ./app:/app
#    redis:
#        image: redis:3.2.0
#
#db:
#    image: postgres
#web:
#    build: .
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    volumes:
#       - .:/www/html
#    ports:
#       - "3000:3000"
#    links:
#       - db


web:
    build: .
    restart: always
    ports:
        - "4200:4200"
        - "4300:4300"

    volumes:
        - ./:/app

